converter = new Showdown.converter()

app_node = new casua.Node document.getElementById('doc-app')

DocApp = casua.defineController (scope) ->

SectionCtrl = casua.defineController (scope) ->
  contentHtml: -> converter.makeHtml scope.get('content')

docs = {}

xhr = new XMLHttpRequest()
for doc in ['controller', 'cst', 'scope', 'arrayscope', 'node']
  xhr.open 'GET', 'docs/' + doc + '.yml', false
  xhr.send()
  docs[doc] = jsyaml.load(xhr.responseText)

template =
  '#side-index':
    '.unit':
      'a.name href="#"': 'Casua {{@version}}'
      'ul.sections':
        'li':
          'a href="#examples"': 'Examples'
    '.units':
      '@child units':
        '.unit':
          'a.name':
            '@attr href': '#{{@id}}'
            '@text': '@title'
          'ul.sections':
            '@child sections':
              'li':
                'a':
                  '@attr href': '#{{@$parent.id}}-{{@id}}'
                  '@text': '@title'
  '#main-content':
    'header':
      'h1.casua': 'Casua'
      'p #short': 'A casual and neat Structured Template and MVVM engine.'
      'p #github':
        'a href="https://github.com/aligo/casua"':
          'span': 'View the Project on GitHub'
          'small': 'aligo/casua'
      'h3#examples': 'Examples'
      'p #todo':
        'a href="https://github.com/aligo/casua/tree/master/examples/"':
          'span': 'Todo , Click'
          'small': 'View Examples on GitHub'
      'p #generated':
        'a href="https://github.com/aligo/casua/tree/master/doc"':
          'span': 'Document App'
          'small': 'This document is also generated by a Casua app.'
    '.units':
      '@child units':
        '@controller': SectionCtrl
        '.unit':
          '@attr id': '@id'
          'h1': '@title'
          'div': 
            '@html': 'contentHtml()'
          '.sections':
            '@child sections':
              '@controller': SectionCtrl
              '.section':
                '@attr id': '{{@$parent.id}}-{{@id}}'
                'h2': '@title'
                'div': 
                  '@html': 'contentHtml()'


new DocApp(
  version: '0.0.2'
  units: [docs.controller, docs.cst, docs.scope, docs.arrayscope, docs.node]
).renderAt app_node, template

hljs.initHighlightingOnLoad()