// Generated by CoffeeScript 1.9.1
(function() {
  var app_node, exampleController, template;

  exampleController = casua.defineController(function(scope) {
    scope.set('was_or_not', 'was not');
    return {
      onClick: function() {
        return scope.set('was_or_not', 'was');
      }
    };
  });

  app_node = new casua.Node(document.getElementById('app'));

  template = {
    'div': {
      '@on click': 'onClick()',
      '@text': 'this {{@was_or_not}} clicked'
    }
  };

  new exampleController().renderAt(app_node, template);

}).call(this);
